test:
    docker run --name mail --rm \
        -e MADDY_HOSTNAME='mx1.localhost' \
        -e MADDY_DOMAIN='localhost' \
        -v $PWD/entrypoint/mail.sh:/entrypoint/mail.sh \
        -v $PWD/tmpl:/tmpl \
        -v $PWD/tls:/data/tls \
        -p 2525:25 \
        -p 2587:587 \
        -p 2465:465 \
        -p 2143:143 \
        -p 2993:993 \
        fj0rd/0x:mx

run tls='' host='example.com' ip='1.2.3.4':
    docker run -d --name maddy \
        --restart=always \
        -e MADDY_HOSTNAME='mx1.{{host}}' \
        -e MADDY_HOSTIP='{{ip}}' \
        -e MADDY_DOMAIN='{{host}}' \
        -e TLS_PROVIDER='{{tls}}' \
        -v $HOME/maddy:/data \
        -p 80:80 \
        -p 25:25 \
        -p 587:587 \
        -p 465:465 \
        -p 143:143 \
        -p 993:993 \
        fj0rd/0x:mx

send:
    docker exec mail \
    swaks --to root@localhost
