del r="2":
    #!/bin/bash
    just deletion {{r}} | curl -sSL -X POST localhost:5000/admin/deletion --data-binary @-

deletion r="1":
    @curl -sSL localhost:5000/admin/deletion?retain={{r}}

list:
    curl localhost:5000/admin/list | jq -r

srv:
    #!/bin/bash
        #-v $PWD/admin.conf:/etc/openresty/admin.conf \
        #-v $PWD/lua:/etc/openresty/lua \
    podman run --rm --name=test-registry \
        -v $HOME/temp/registry:/var/lib/registry \
        -v $PWD/entrypoint.sh:/entrypoint.sh \
        -v $PWD/nginx.conf:/etc/openresty/nginx.conf \
        -e HTPASSWD=adm:123 \
        -p 5000:5000 \
        fj0rd/0x:registry

restart:
    podman rm -f test-registry
    just srv

clean:
    podman rm -f test-registry
    rm -rf $HOME/temp/registry

sync:
    #!/bin/bash
    pod=$(kubectl get pod -l app.kubernetes.io/instance=registry -o jsonpath="{.items[0].metadata.name}")
    kubectl cp lua/list.lua $pod:/etc/openresty/lua/list.lua
    kubectl cp lua/deletion.lua $pod:/etc/openresty/lua/deletion.lua
    kubectl cp daily-job $pod:/daily-job
    kubectl cp daily-clean $pod:/daily-clean
    kubectl exec $pod -- /opt/openresty/bin/openresty -s reload


push:
    #!/bin/bash
    podman tag 0x:registry localhost:5000/0x:registry
    podman push localhost:5000/0x:registry
    podman rmi localhost:5000/0x:registry

    podman tag 0x:latest localhost:5000/0x:latest
    podman push localhost:5000/0x:latest
    podman rmi localhost:5000/0x:latest

    podman tag io:latest localhost:5000/io:latest
    podman push localhost:5000/io:latest
    podman rmi localhost:5000/io:latest

    podman tag io:latest localhost:5000/a/b/c/io:latest
    podman push localhost:5000/a/b/c/io:latest
    podman rmi localhost:5000/a/b/c/io:latest

    podman tag io:latest localhost:5000/a/b/c/io:xyz
    podman push localhost:5000/a/b/c/io:xyz
    podman rmi localhost:5000/a/b/c/io:xyz

    podman tag ubuntu:latest localhost:5000/docker.io/ubuntu:latest
    podman push localhost:5000/docker.io/ubuntu:latest
    podman rmi localhost:5000/docker.io/ubuntu:latest

    podman tag 0x:latest localhost:5000/docker.io/ubuntu:test
    podman push localhost:5000/docker.io/ubuntu:test
    podman rmi localhost:5000/docker.io/ubuntu:test

    podman tag 0x:registry localhost:5000/docker.io/ubuntu:test1
    podman push localhost:5000/docker.io/ubuntu:test1
    podman rmi localhost:5000/docker.io/ubuntu:test1
