#!/usr/bin/with-contenv sh

echo >&2 "starting coredns"

if [ ! -f /app/dnsconfig/Corefile ]; then
cat << EOF > /app/dnsconfig/Corefile
. {

    import zones/*

    forward . 8.8.8.8 8.8.4.4 {
        policy sequential
        prefer_udp
        expire 10s
    }

    reload 15s
    cache 120
    errors
    log
}
EOF
fi

mkdir -p /app/dnsconfig/zones

if [ ! -f /app/dnsconfig/zones/example ]; then
cat << EOF >  /app/dnsconfig/zones/example
template IN A self {
    answer "{{ .Name }} IN A 127.0.0.1"
    fallthrough
}

# 1-2-3-4.ip A 1.2.3.4
template IN A ip {
    match (^|[.])(?P<a>[0-9]*)-(?P<b>[0-9]*)-(?P<c>[0-9]*)-(?P<d>[0-9]*)[.]ip[.]$
    answer "{{ .Name }} 60 IN A {{ .Group.a }}.{{ .Group.b }}.{{ .Group.c }}.{{ .Group.d }}"
    fallthrough
}
EOF
fi

exec /usr/local/bin/coredns -conf /app/dnsconfig/Corefile 2>&1
