#!/usr/bin/with-contenv sh

echo >&2 "starting nebula"

cd /app
config=${NEBULA_CONFIG:-/app/config.yaml}

if [ ! -f /app/ca.crt ]; then
    nebula-cert ca -name "${NETWORK_ID}"
fi

if [ ! -f /app/lighthouse.crt ]; then
    nebula-cert sign -name lighthouse -ip ${HOST_IP}/${VCIDR:-16}
fi

if [ ! -f $config ]; then
    cat /app/config.yaml.tmpl | yq e '
        .listen.port = '${HOST_PORT:-51821}'
        | .pki.cert = "./lighthouse.crt"
        | .pki.key = "./lighthouse.key"
        | .lighthouse.am_lighthouse = true
        | .static_host_map["'${VHOST}'"] += ["'${HOST_IP}:${HOST_PORT:-51821}'"]
    ' - > $config
fi


exec /usr/local/bin/nebula -config $config 2>&1
