#!/usr/bin/with-contenv sh

echo >&2 "starting nebula"

cd /world
config=${NEBULA_CONFIG:-/world/config.yaml}
vcidr=${VCIDR:-16}
vgroup=${VGROUPS:-default}
port=${HOST_PORT:-51821}

echo config=$config groups="$vgroup"
echo network=${NETWORK_ID} cidr=$VHOST/$vcidr endpoint=$HOST_IP:$HOST_PORT

if [ ! -f /world/ca.crt ]; then
    nebula-cert ca -name "${NETWORK_ID}"
fi

if [ ! -f /world/lighthouse.crt ]; then
    echo nebula-cert sign -name lighthouse -ip "${VHOST}/${vcidr}" -groups "${vgroup}"
    nebula-cert sign -name lighthouse -ip "${VHOST}/${vcidr}" -groups "${vgroup}"
fi

if [ ! -f $config ]; then
    cat /config.yaml.tmpl | yq e '
        .listen.port = '${port}'
        | .pki.cert = "./lighthouse.crt"
        | .pki.key = "./lighthouse.key"
        | .lighthouse.am_lighthouse = true
    ' - > $config
fi


exec /usr/local/bin/nebula -config $config 2>&1
