#!/usr/bin/with-contenv sh

echo "${EXTERNAL_IP} ${DOMAIN}" >> /etc/hosts
echo "${DOMAIN:-localhost}" >> /etc/mailname

sed -i 's/USER@DOMAIN\.TLD/'"${MASTER}@${DOMAIN}"'/' /etc/postfix/aliases
postalias /etc/postfix/aliases

echo >&2 "starting postfix"
exec /usr/sbin/postfix start 2>&1

