apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify
  namespace: argo
  labels:
    app: notify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      namespace: argo
      labels:
        app: notify
    spec:
      containers:
      - name: notify
        image: fj0rd/0x:notify-gateway
        imagePullPolicy: IfNotPresent
        env:
        - name: ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: webhook-endpoints
              key: wechat
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: notify
  namespace: argo
  labels:
    app: notify
spec:
  selector:
    app: notify
  ports:
  - name: app
    protocol: TCP
    port: 80
    targetPort: 3000
