FROM fj0rd/scratch:tailscale as assets

FROM fj0rd/0x:wg

COPY --from=assets /linux_amd64 /usr/local/bin
COPY entrypoint.client.sh /entrypoint.sh

ENV WG_QUICK_USERSPACE_IMPLEMENTATION=boringtun
ENV HOST=
ENV TOKEN=
ENTRYPOINT ["/entrypoint.sh"]
