test file="justfile" path="justfile":
    curl localhost:8080/upload/{{path}} -T {{file}}

test1 file="justfile" path="justfile":
    curl -X POST localhost:8080/upload/{{path}} --data-binary @{{file}}

srv:
    #!/bin/bash
        #-v $PWD/entrypoint.sh:/entrypoint.sh
        #-e ed25519_root=123 \
    podman run --rm --name=test -p 8080:80 \
        -v $PWD/location:/etc/openresty/location \
        -v $PWD/config/lua:/etc/openresty/lua \
        -v $PWD/config/nginx.conf:/etc/openresty/nginx.conf \
        0x:or

