test-entrypoint:
    podman run --rm -it --name test-entrypoint \
        --cap-add=SYS_ADMIN --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
        -e https_proxy=http://172.178.5.21:7890 \
        -e ed25519_root=AAAAC3NzaC1lZDI1NTE5AAAAIK2Q46WeaBZ9aBkS3TF2n9laj1spUkpux/zObmliHUOI \
        -e vector_xf=/etc/vector/xx \
        -v $PWD/entrypoint/vector.sh:/entrypoint/vector.sh \
        0x:utils
