#!/usr/bin/with-contenv sh

bash /generate_config_js.sh > /usr/share/nginx/html/config.js

echo ">>>> backend set to: $BACKEND_URL <<<<<"

echo >&2 "starting nginx"

envsubst < /etc/nginx/nginx.conf.tmpl > /etc/nginx/nginx.conf

exec /opt/nginx/sbin/nginx 2>&1
