#!/usr/bin/with-contenv sh

bash /generate_config_js.sh > /usr/share/nginx/html/config.js

echo ">>>> backend set to: $BACKEND_URL <<<<<"

echo >&2 "starting nginx"


sed -e 's!${WEB_PORT}!'"${WEB_PORT}"'!' \
    -e 's!${API_PORT}!'"${API_PORT}"'!' \
    /etc/nginx/nginx.conf.tmpl \
  > /etc/nginx/nginx.conf

exec /opt/nginx/sbin/nginx 2>&1
