#!/usr/bin/with-contenv sh

echo >&2 "starting coredns"

if [ ! -f /app/config/dnsconfig/Corefile ]; then
cat << EOF > /app/config/dnsconfig/Corefile
. {
    reload 15s

        import /app/config/dnsconfig/zones/*

        hosts /app/config/dnsconfig/netmaker.hosts {
            fallthrough
        }

        forward . 8.8.8.8 8.8.4.4

    log
}
EOF
fi

touch /app/config/dnsconfig/netmaker.hosts

mkdir -p /app/config/dnsconfig/zones

if [ ! -f /app/config/dnsconfig/zones/example ]; then
cat << EOF >  /app/config/dnsconfig/zones/example
template IN A example {
    answer "{{ .Name }} IN A 10.0.0.1"
    fallthrough
}

# 1-2-3-4.ip A 1.2.3.4
template IN A ip {
    match (^|[.])(?P<a>[0-9]*)-(?P<b>[0-9]*)-(?P<c>[0-9]*)-(?P<d>[0-9]*)[.]ip[.]$
    answer "{{ .Name }} 60 IN A {{ .Group.a }}.{{ .Group.b }}.{{ .Group.c }}.{{ .Group.d }}"
    fallthrough
}
EOF
fi

exec /app/coredns -conf /app/config/dnsconfig/Corefile 2>&1
