#!/usr/bin/with-contenv sh

echo >&2 "starting coredns"

cat << EOF > /app/config/dnsconfig/Corefile
. {
    reload 15s
    hosts /app/config/dnsconfig/netmaker.hosts {
        fallthrough
    }
    forward . 8.8.8.8 8.8.4.4
    log
}
EOF

touch /app/config/dnsconfig/netmaker.hosts

exec /app/coredns -conf /app/config/dnsconfig/Corefile 2>&1
