test:
    docker run --name mail --rm \
        -e HOST='' \
        -e EXTERNAL_IP=127.0.0.1 \
        -e MASTER=root \
        -v $PWD/entrypoint/mail.sh:/entrypoint/mail.sh \
        -v $PWD/data/mail:/var/spool/mail \
        -v $PWD/data/opendkim:/etc/opendkim \
        -p 25:25 \
        -p 465:465 \
        -p 587:587 \
        -p 110:110 \
        -p 995:995 \
        -p 143:143 \
        -p 993:993 \
        fj0rd/0x:mail

run:
    docker run -d --restart=always \
        --name mail \
        -e DOMAIN=lizzie.fun \
        -e EXTERNAL_IP=67.218.158.11 \
        -e MASTER=root \
        -v $PWD/mail:/var/spool/mail \
        -p 25:25 \
        -p 465:465 \
        -p 587:587 \
        -p 110:110 \
        -p 995:995 \
        -p 143:143 \
        -p 993:993 \
        fj0rd/0x:mail
