test:
    rm -rf data/mail
    mkdir -p data/mail
    docker run --name mail --rm \
        -e HOST='localhost' \
        -e EXTERNAL_IP=127.0.0.1 \
        -e MASTER=root \
        -e OPENDKIM='' \
        -v $PWD/entrypoint/mail.sh:/entrypoint/mail.sh \
        -v $PWD/tmpl:/tmpl \
        -v $PWD/data/mail:/var/mail \
        -v $PWD/data/opendkim:/etc/opendkim \
        -p 2525:25 \
        -p 2143:143 \
        -p 2993:993 \
        fj0rd/0x:mx

run:
    docker run -d --restart=always \
        --name mail \
        -e DOMAIN=lizzie.fun \
        -e EXTERNAL_IP=67.218.158.11 \
        -e MASTER=root \
        -v $PWD/mail:/var/mail \
        -p 25:25 \
        -p 143:143 \
        -p 993:993 \
        -p 465:465 \
        -p 587:587 \
        -p 110:110 \
        -p 995:995 \
        fj0rd/0x:mx

send:
    docker exec mail \
    swaks --to root@localhost
