test file="justfile" path="justfile":
    curl -u admin:123 -X POST localhost:8020/upload/a/b/c/{{path}} --data-binary @{{file}}

test1 file="justfile" path="justfile":
    curl localhost:8020/upload/b/{{path}} -T {{file}}

srv:
    #!/bin/bash
        #-v $PWD/entrypoint.sh:/entrypoint.sh
    podman run --rm -it --name=test -p 8020:80 \
        -v $PWD/entrypoint/openresty.sh:/entrypoint/openresty.sh \
        -v $PWD/config/nginx.conf.tmpl:/etc/openresty/nginx.conf.tmpl \
        -v $PWD/config/test.site.json:/etc/openresty/test.site.json \
        -e ROUTEFILE=/etc/openresty/test.location.json \
        -e SITEFILE=/etc/openresty/test.site.json \
        -e ed25519_root=123 \
        -e UPLOAD_ROOT=upload/ \
        -e HTPASSWD=admin:123 \
        0x:openresty bash

