[general]
port = 6432
admin_username = "pgcat"
admin_password = "pgcat"

[pools.bar]
pool_mode = "session"

[pools.bar.users.0]
pool_size = 12
username = "foo"
password = "foo"

[pools.bar.shards.0]
database = "foo"
servers = [
    ["127.0.0.1", 5432, "primary"],
]
