name: postgres 16

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main, pg, pg16 ]
  workflow_dispatch:
    inputs: {}

env:
  REGISTRY: docker.io
  IMAGE_NAME: fj0rd/0x


jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ !endsWith(github.event.head_commit.message, '~') }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: fj0rd
          password: ${{ secrets.DOCKER }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build pg_rx
        if: ${{ !contains(github.event.head_commit.message, '-pg_rx') }}
        uses: docker/build-push-action@v4
        with:
          context: postgres
          file: postgres/rx.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pg_rx
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build pg_ext
        if: ${{ !contains(github.event.head_commit.message, '-pg_ext') }}
        uses: docker/build-push-action@v4
        with:
          context: postgres
          file: postgres/ext.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pg_ext
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build pg 16
        uses: docker/build-push-action@v4
        with:
          context: postgres
          file: postgres/16.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pg
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build pgis
        uses: docker/build-push-action@v4
        with:
          context: postgres
          file: postgres/gis.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pgis
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASEIMAGE=fj0rd/0x:pg

