name: postgres 17

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ pg17 ]
  workflow_dispatch:
    inputs: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: fj0r/0x


jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ !endsWith(github.event.head_commit.message, '~') }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: fj0r
          password: ${{ secrets.GHCR_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build pg_rx
        if: ${{ !contains(github.event.head_commit.message, '-pg_rx') }}
        uses: docker/build-push-action@v4
        with:
          context: postgres
          file: postgres/rx.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pg17_rx
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PG_VERSION_MAJOR=17

      - name: Build pg_ext
        if: ${{ !contains(github.event.head_commit.message, '-pg_ext') }}
        uses: docker/build-push-action@v4
        with:
          context: postgres
          file: postgres/ext.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pg17_ext
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PG_VERSION_MAJOR=17
            BASEIMAGE=ghcr.io/fj0r/0x:pg17_rx

      - name: Build pg 17
        uses: docker/build-push-action@v4
        with:
          context: postgres
          file: postgres/17.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pg17
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PG_VERSION_MAJOR=17
            BASEIMAGE=ghcr.io/fj0r/0x:pg17_ext

      - name: Build pgis
        uses: docker/build-push-action@v4
        with:
          context: postgres
          file: postgres/gis.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:pgis17
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASEIMAGE=ghcr.io/fj0r/0x:pg17

